### ISSUE TITLE
ShellLink.TargetPath value different than Explorer's

### ISSUE THREAD

**Issue by talenthe** [dahall/Vanara#205]
**Describe the bug**
ShellLink will return a fake path. Actual path is "C:\Program Files\Microsoft Office\root\Office16\WINWORD.EXE"
![image](https://user-images.githubusercontent.com/73872039/106841882-e7eff380-66dd-11eb-949d-2071cb44065d.png)

![image](https://user-images.githubusercontent.com/73872039/106841784-b6772800-66dd-11eb-9284-cbad20e506a9.png)

**What code is involved**
```csharp
ShellLink Link = new ShellLink("Desktop/Word.lnk")
```

**Expected behavior**
Correct path

**Screenshots**

**Comment by dahall** [comment]
Will you check your machine to see if that path, that you said is incorrect, actually exists and if the Word executable is there instead of where you show on the first screen shot? The reason I ask is that on my machine, Word is actually at the location your second screen shot shows. When I try this looking at the Word.lnk file supporting my Start Menu entry (mine's at `"C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Word.lnk"`), it shows the same as yours with ShellLink, but it shows the same when I look at the properties window.

**Comment by talenthe** [comment]
I found this issue will occur if my program is base on X86 and OS is X64

**Comment by talenthe** [comment]
And Office is X64 version

**Comment by dahall** [comment]
I've checked the code and don't find anything wrong. My guess is that this is the effect of WOW and how it translates file and registry settings when mixing 32 and 64-bit. It appears [others have seen this too](https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/6f2e7920-50a9-459d-bfdd-316e459e87c0/ishelllink-getpath-returns-wrong-folder-for-64-bit-application-when-called-from-32-bit-application?forum=windowsgeneraldevelopmentissues) and [here](https://www.codeproject.com/Tips/998952/Using-bit-Shortcuts-from-a-bit-Application).
