### ISSUE TITLE
Error NETSDK1136: The target platform must be set to Windows (User32 only)

### ISSUE THREAD

**Issue by netcorefan1** [dahall/Vanara#207]
Thanks for bringing this to my attention. I have resolved it in the latest commit for 3.3.3. It will release in the next few days.

_Originally posted by @dahall in https://github.com/dahall/Vanara/issues/200#issuecomment-767594942_

It appears to be that this issue still persist in 3.3.3.
Thanks

**Comment by dahall** [comment]
Are you building this separately or using the NuGet package?

**Comment by dahall** [comment]
Ha! Sorry. I forgot to mention that I specifically selected the framework "net5.0-windows" since the P/Invoke calls only work on Windows. To fix the error in your project, you also have to select that as a target platform. "net5.0", by itself, will not work. Now that .NET targets so many platforms, they have added this platform specifier that is supposed to be included if the package only works on one platform.

**Comment by netcorefan1** [comment]
For me is fine to change the target framework, but I am wondering if may cause additional overhead considering that will come into the game WinForms and Wpf Assemblies for which sincerely I don't any idea on what possible relation may have pinvoke with such managed assemblies.

**Comment by dahall** [comment]
It is usually some reference to something like Bitmap, ImageList, Image, Control, Window, etc. in an extension method where the WinForm or WPF assemblies are needed.
