### ISSUE TITLE
Allowing to pass NULL to optional arguments in pinvoke 

### ISSUE THREAD

**Issue by yuval7451** [dahall/Vanara#220]
While trying to use the function NtCreateTransaction or any function with optional parameters, I'm unable to pass NULL / 0 / IntPtr.Zero to any of the optional parameters, 
seems like this should be implemented due to reserved / unnecessary parameters in winapi.

**Comment by dahall** [comment]
The definition for `NtCreateTransaction` in the library is:
```cs
[DllImport(Lib.NtDll, SetLastError = false, CharSet = CharSet.Auto)]
public static extern NTStatus NtCreateTransaction(out SafeTransactionHandle TransactionHandle,
   ACCESS_MASK DesiredAccess, ref OBJECT_ATTRIBUTES ObjectAttributes, in Guid Uow,
   SafeTransactionManagerHandle TmHandle, uint CreateOptions, [Optional] uint IsolationLevel,
   [Optional] uint IsolationFlags, in long Timeout, in UNICODE_STRING Description);
```
I see, looking more closely at the definition, that most of the parameters are optional. In most cases, especially with newer sections of the library, I have tried to create overloads for functions like this so that there is at least one definition that supports all the optional parameters. I have chosen not to do this using pointers, like some other libraries, as many C#/.NET developers are unfamiliar with them. I'll dig into NTDLL to see where I can add these overloads.

**Comment by dahall** [comment]
I have updated all functions in `Vanara.PInvoke.NtDll` that had incomplete parameter attributes and have added overloads for those that needed _nullable_ optional attributes. You'll see these changes in the 3.3.7 release or you can pull them from the AppVeyor temporary NuGet repository (see homepage for details).
