### ISSUE TITLE
Is there an option to replace every "in" and "out" by "ref" to support VB?

### ISSUE THREAD

**Issue by scenevista** [dahall/Vanara#234]
Due to the syntax differences between C# and VB.NET, some features in C# are not supported by VB.NET, such as the keyword "in" and "out" before the argument, and as the result of this almost everything of Vanara doesn't support VB.NET. VB.NET supports the keyword "ByRef", which is equivalent to "ref" in C#. Is there an option to replace every "in" and "out" by "ref"?

**Comment by dahall** [comment]
Across the libraries, there are thousands of functions whose definitions already use the `in` or `out` attribute. Changing them at this point would introduce, in my opinion, far too many breaking changes. Because C# does not allow for overloaded methods to have a parameter in one with an `in` attribute and another with a `ref` attribute, what I could do is introduce functions whose prefix is something like `VB` so that there would be something similar to an overload that has functioning attributes just for VB. What are your thoughts?

**Comment by scenevista** [comment]
You mean, for example, we can see both `void Example(in int arg1, out int arg2);` and `void ExampleVB(ref int arg1, ref int arg2);` in the library? This is a good idea, but the work's still gonna be a litle **HUGE**.😜

**Comment by dahall** [comment]
Yes, precisely. Another option would be to subclass the namespace (e.g. `Vanara.PInvoke.Kernel32.VB`) and put the methods there. I think I prefer this over mangling the name and it provides better searchability.

The work would be mammoth. In fact, I’d likely ask people like you that want this to submit PRs for those functions that are most critical rather than doing the work myself. I'm not a VB programmer and would not have the experience to adequately test.

**Comment by scenevista** [comment]
Or maybe, we can write another wrapper, repacking the functions and delegates to make them avaliable for both VB and C#, for each original library?

```
namespace CSLib1
{
    public class Class1
    {
        public static void Test(out int a)
        {
            a = 1;
        }

    }
}
```
```
namespace CSLib1VB
{
    public class Class1
    {
        public static void Test(ref int a)
        {
            CSLib1.Class1.Test(out a);
        }

    }
}

```

**Comment by dahall** [comment]
Yes. I'd also want to publish them in a separate NuGet package. This model would accommodate a simple search and replace approach.

**Comment by scenevista** [comment]
Agree.
