### ISSUE TITLE
ShellLink should not rely on System.Windows.Forms

### ISSUE THREAD

**Issue by zhuxb711** [dahall/Vanara#245]
**Describe the bug**
ShellLink should not rely on System.Windows.Forms because System.Windows.Forms could not be used in ARM/ARM64. So if ShellLink or the others component rely on it, we could not use it on .NET 5 ARM. I think it would be great if we could remove the System.Windows.Forms dependency in vanara

**What code is involved**
None

**Expected behavior**
Varana should be work in All kinds of device.

**Screenshots**
None

**Comment by dahall** [comment]
`System.Windows.Forms` as an assembly dependency only exists for .NET Framework builds 2.0, 3.0, 4.0 and 4.5. Which is your project using?

`ShellLink` uses 3 references from `System.Windows.Forms`: `IWin32Window` (constructor), `Keys` (`HotKey` prop), and `FormWindowState` (`ShowState` prop). Changing any of those is a pretty significant and breaking change. Rather than making the change, I think I'll let this sit for a while to see if it gets upvoted.

**Comment by zhuxb711** [comment]
My project is .NET Framework 4.8....Ok lets see if it gets upvoted.
