### ISSUE TITLE
ShellFileOperations will not report the progress normally if OperationFlags.AddUndoRecord or OperationFlags.RecycleOnDelete was set

### ISSUE THREAD

**Issue by zhuxb711** [dahall/Vanara#246]
**Describe the bug**
ShellFileOperations will not report the progress normally if OperationFlags.AddUndoRecord or OperationFlags.RecycleOnDelete was set.
It will report 0% and jump to 100% (1 file)
It will report 0% and jump to 50% then jump to 100% (2 files)

**What code is involved**
None

**Expected behavior**
Report as normal

**Screenshots**
None

**Comment by dahall** [comment]
I'll look again at my code, but this sounds like a Windows API problem. Have you done any searching on workarounds associated with the native API?

**Comment by zhuxb711** [comment]
The only thing I found is [this](https://stackoverflow.com/questions/57461683/track-progress-of-moving-to-recycle-bin-on-windows)

**Comment by dahall** [comment]
`OperationFlags.RecycleOnDelete` should only show the progress at the file count level since it not actually removing anything. The file is only tagged by the shell as residing in the recycle bin. `OperationFlags.AddUndoRecord` is simply an indicator to add the shell item to a system undo stack, so I would expect that it also operates on the file count level. If you take a long listing of files in Windows Explorer and delete them, you'll see this same behavior. If you hard delete them (removing the RecycleOnDelete flag), then you'll see the byte-level progress.

**Comment by dahall** [comment]
@zhuxb711 Please close if this addressed your question.

**Comment by zhuxb711** [comment]
Thanks.
