### ISSUE TITLE
Add Create method for types MONITORINFO and MONITORINFOEX 

### ISSUE THREAD

**Issue by psulek** [dahall/Vanara#371]
**Is your feature request related to a problem? Please describe.**
Type `MONITORINFO` and `MONITORINFOEX` both have field `cbSize`, which as described in docs must be set via `sizeof()` before calling method `GetMonitorInfo()` (both overloads). 

This can be confusing for new users (especially new C#/dotnet coders) that calling `var info = new MONITORINFO();` is not enough, and required construct is: `var info = new MONITORINFO{ cbSize = sizeof(MONITORINFO) };`

Also there can be (depends on user code context) error like: `'MONITORINFO' does not have a predefined size, therefore sizeof can only be used in an unsafe context`.

**Describe the additions or enhancements you'd like**
Create static method `Create()` for both types `MONITORINFO` and `MONITORINFOEX` which will set `cbSize` automatically for user.

**Comment by dahall** [comment]
Thank you for submitting a PR. In many places in the project I have used the `public static STRUCTNAME Default => new() { cbSize = (uint)Marshal.SizeOf(typeof(STRUCTNAME)) }` pattern, rather than the `Create` method pattern. For consistency, will you adapt your PR to use the library pattern and then I'll accept?

**Comment by psulek** [comment]
Sure, sounds good!
