### ISSUE TITLE
Kernel32 GetProcAddress for 64its

### ISSUE THREAD

**Issue by iR3SH** [dahall/Vanara#478]
Hi,
I'm trying to use the function GetProcAddress, when i run my application in 32Bits everthing works, but not when i launch it in Any CPU or 64Bits

Could you make the method compatible with 64Bits ?

Thanks :)

**Comment by dahall** [comment]
Which overload are you using and what exception or result code are you getting?

**Comment by tajbender** [comment]
I found something, maybe this is helpful:

[StackOverflow: GetProcAddress function in C++](https://stackoverflow.com/questions/6031431/getprocaddress-function-in-c)

[StackOverflow:](https://stackoverflow.com/a/6031589/23498452)

``lpGetNumber = (LPGETNUMBER)GetProcAddress((HMODULE)hDLL, "GetNumber");```

> Checking return codes and calling GetLastError() will set you free. You should be checking return codes twice here. You are actually checking return codes zero times.
> 
> hDLL = LoadLibrary(L"MYDLL.DLL");
> Check hDLL. Is it NULL? If so, call GetLastError() to find out why. It may be as simple as "File Not Found".
> 
> lpGetNumber = (LPGETNUMBER)GetProcAddress((HMODULE)hDLL, "GetNumber");
> If lpGetNumber is NULL, call GetLastError(). It will tell you why the proc address could not be found. There are a few likely scenarios:

**Comment by tajbender** [comment]
Another Hint: https://stackoverflow.com/questions/10250323/getprocaddress-null-is-returned?rq=3

**Comment by iR3SH** [comment]
Thanks for all of your answer, i use it in a C# Library project, So first i Load my Library like this :
SafeHINSTANCE safeModule = LoadLibraryEx(DllUrl);
Then i want to load the functions of the dll like this GetProcAddress(safeModule, "CCAPIConnectConsole")
But then i look if any load of functions are loaded correclty

`        
safeModule = LoadLibrary(DllUrl);
CCAPIFunctionsList.Add(GetProcAddress(safeModule, "CCAPIConnectConsole"));
CCAPIFunctionsList.Add(GetProcAddress(safeModule, "CCAPIDisconnectConsole"));
CCAPIFunctionsList.Add(GetProcAddress(safeModule, "CCAPIGetConnectionStatus"));
CCAPIFunctionsList.Add(GetProcAddress(safeModule, "CCAPISetBootConsoleIds"));
CCAPIFunctionsList.Add(GetProcAddress(safeModule, "CCAPISetConsoleIds"));
CCAPIFunctionsList.Add(GetProcAddress(safeModule, "CCAPISetMemory"));
CCAPIFunctionsList.Add(GetProcAddress(safeModule, "CCAPIGetMemory"));
CCAPIFunctionsList.Add(GetProcAddress(safeModule, "CCAPIGetProcessList"));
CCAPIFunctionsList.Add(GetProcAddress(safeModule, "CCAPIGetProcessName"));
CCAPIFunctionsList.Add(GetProcAddress(safeModule, "CCAPIGetTemperature"));
CCAPIFunctionsList.Add(GetProcAddress(safeModule, "CCAPIShutdown"));
CCAPIFunctionsList.Add(GetProcAddress(safeModule, "CCAPIRingBuzzer"));
CCAPIFunctionsList.Add(GetProcAddress(safeModule, "CCAPISetConsoleLed"));
CCAPIFunctionsList.Add(GetProcAddress(safeModule, "CCAPIGetFirmwareInfo"));
CCAPIFunctionsList.Add(GetProcAddress(safeModule, "CCAPIVshNotify"));
CCAPIFunctionsList.Add(GetProcAddress(safeModule, "CCAPIGetNumberOfConsoles"));
CCAPIFunctionsList.Add(GetProcAddress(safeModule, "CCAPIGetConsoleInfo"));
CCAPIFunctionsList.Add(GetProcAddress(safeModule, "CCAPIGetDllVersion"));

private bool IsCCAPILoaded()
        {
            for (int i = 0; i < CCAPIFunctionsList.Count; i++)
                if (CCAPIFunctionsList.ElementAt(i) == IntPtr.Zero)
                    return false;
            return true;
        }`

**Comment by tajbender** [comment]
Please try this:https://csharp.hotexamples.com/fr/examples/-/getDllVersionDelegate/-/php-getdllversiondelegate-class-examples.htmlAm 06.08.2024 10:49 schrieb iR3SH ***@***.***>:
Thanks for all of your answer, i use it in a C# Library project, So first i Load my Library like this :
SafeHINSTANCE safeModule = LoadLibraryEx(DllUrl);
Then i want to load the functions of the dll like this GetProcAddress(safeModule, "CCAPIConnectConsole")
But then i look if any load of functions are loaded correclty
`
safeModule = LoadLibrary(DllUrl);
CCAPIFunctionsList.Add(GetProcAddress(safeModule, "CCAPIConnectConsole"));
CCAPIFunctionsList.Add(GetProcAddress(safeModule, "CCAPIDisconnectConsole"));
CCAPIFunctionsList.Add(GetProcAddress(safeModule, "CCAPIGetConnectionStatus"));
CCAPIFunctionsList.Add(GetProcAddress(safeModule, "CCAPISetBootConsoleIds"));
CCAPIFunctionsList.Add(GetProcAddress(safeModule, "CCAPISetConsoleIds"));
CCAPIFunctionsList.Add(GetProcAddress(safeModule, "CCAPISetMemory"));
CCAPIFunctionsList.Add(GetProcAddress(safeModule, "CCAPIGetMemory"));
CCAPIFunctionsList.Add(GetProcAddress(safeModule, "CCAPIGetProcessList"));
CCAPIFunctionsList.Add(GetProcAddress(safeModule, "CCAPIGetProcessName"));
CCAPIFunctionsList.Add(GetProcAddress(safeModule, "CCAPIGetTemperature"));
CCAPIFunctionsList.Add(GetProcAddress(safeModule, "CCAPIShutdown"));
CCAPIFunctionsList.Add(GetProcAddress(safeModule, "CCAPIRingBuzzer"));
CCAPIFunctionsList.Add(GetProcAddress(safeModule, "CCAPISetConsoleLed"));
CCAPIFunctionsList.Add(GetProcAddress(safeModule, "CCAPIGetFirmwareInfo"));
CCAPIFunctionsList.Add(GetProcAddress(safeModule, "CCAPIVshNotify"));
CCAPIFunctionsList.Add(GetProcAddress(safeModule, "CCAPIGetNumberOfConsoles"));
CCAPIFunctionsList.Add(GetProcAddress(safeModule, "CCAPIGetConsoleInfo"));
CCAPIFunctionsList.Add(GetProcAddress(safeModule, "CCAPIGetDllVersion"));
private bool IsCCAPILoaded()
{
for (int i = 0; i < CCAPIFunctionsList.Count; i++)
if (CCAPIFunctionsList.ElementAt(i) == IntPtr.Zero)
return false;
return true;
}`

**Comment by iR3SH** [comment]
This was my bad, i'm tryng to load an 32Bits Library in an 64Bits tool, it can't work i think

**Comment by dahall** [comment]
> This was my bad, i'm tryng to load an 32Bits Library in an 64Bits tool, it can't work i think

https://stackoverflow.com/questions/2265023/load-32-bit-dll-library-in-64-bit-application

**Comment by dahall** [comment]
Also, for functions like this that use a NULL handle to report failure, you can use Win32Error.ThrowLastErrorIfInvalid
```cs
CCAPIFunctionsList.Add(Win32Error.ThrowLastErrorIfInvalid(GetProcAddress(safeModule, "CCAPIGetDllVersion")));
```

**Comment by tajbender** [comment]
> Also, for functions like this that use a NULL handle to report failure, you can use Win32Error.ThrowLastErrorIfInvalid
> 
> ```cs
> CCAPIFunctionsList.Add(Win32Error.ThrowLastErrorIfInvalid(GetProcAddress(safeModule, "CCAPIGetDllVersion")));
> ```

@dahall: Another unrelated Question:

Does this always work?

Or does this only work on specific DLLs, like `Shel32`, `Kernel32` etc.?

**Comment by dahall** [comment]
Any handle in Vanara that supports the `IHandle` interface will work with the `Win32Error.ThrowLastErrorIfInvalid` method.

**Comment by tajbender** [comment]
I've updated the PR:

https://github.com/dahall/Vanara/pull/499#issuecomment-2572766353

Just leave a short note for David, so he can see that this works for your build.

Regards,
Thorsten

________________________________
From: 祝 若凡 ***@***.***>
Sent: Monday, January 6, 2025 10:38
To: Thorsten Jung ***@***.***>
Subject: Re: Vanara WinUI Bugfix

Hi Thorsten,

I think it's normal for OneDrive folder.
OneDrive folder is not a common folder, which is actually a "virtual" folder that provided by OneDrive app. Which I think that cause the delay. From the video, the delay is totally acceptable. No need to concern it😁

Best regards,
Ruofan


________________________________
From: Thorsten Jung ***@***.******@***.***>>
Sent: 1/5/2025 4:20:16 PM +08:00
To: 祝 若凡 ***@***.******@***.***>>
Subject: Re: Vanara WinUI Bugfix

Watch the video.

This is the "Bug" in electrifier. See the Delay, when I navigate to "Thorsten - Personal".

All other Libraries enumerate fast, except "Thorsten - Personal".

https://github.com/tajbender/electrifier.v1.24.git
[https://repository-images.githubusercontent.com/755072902/cfce01c9-9e14-469a-9d18-ae3eee0d2fe0]<https://github.com/tajbender/electrifier.v1.24.git>
GitHub - tajbender/electrifier.v1.24: Re-Implementing electrifier 2024<https://github.com/tajbender/electrifier.v1.24.git>
Re-Implementing electrifier 2024. Contribute to tajbender/electrifier.v1.24 development by creating an account on GitHub.
github.com


This is my Implementation using WinUI3 and Vanara. It's still in Development, though...

Regards,
Thorsten



________________________________
From: 祝 若凡 ***@***.***>
Sent: Sunday, January 5, 2025 09:02
To: Thorsten Jung ***@***.***>
Subject: Re: Vanara WinUI Bugfix

Hi Thorsten,

I'm not quite understand your video. Could you please describe the problem so that I could share the solution if I have met it before. Thanks.

Best regards,
Ruofan


________________________________
发件人: Thorsten Jung ***@***.***>
发送时间: 星期日, 一月 5, 2025 3:29:31 下午
收件人: ***@***.*** ***@***.***>
主题: Re: Vanara WinUI Bugfix

Hi,

I hope you can enjoy this weekend; we've got snow here in German⛄

Okay, I sent a video of the bug I have in electrifier. That is without your fix...

However, is this the same problem that you have?

Can you confirm?

Thank you,
Thorsten


________________________________
From: Thorsten Jung ***@***.***>
Sent: Sunday, January 5, 2025 08:24
To: ***@***.*** ***@***.***>
Subject: Vanara WinUI Bugfix
