### ISSUE TITLE
Create static method for structures which require initialization

### ISSUE THREAD

**Issue by NN---** [dahall/Vanara#8]
PInvoke library has a convenient Create method for structures where there is a need for some default initialization.
This library should have this too.

For instance:
https://github.com/AArnott/pinvoke/blob/bc4c6830f1918f5af28e76e075dd0750f27d3c61/src/Kernel32/desktop/Kernel32%2BStartupInfo.cs#L127

**Comment by dahall** [comment]
I can definitely do this for this particular structure. I have done it elsewhere in the library as constructors and would likely follow that same pattern here.

**Comment by NN---** [comment]
The problem is that you cannot overload empty constructor in struct, so using static method is a better way IMO.

**Comment by chrpai** [comment]
I think this would help me also.  My P/Invoke isn't that strong and I'm trying to get my feet wet with Authz API by calling AuthzEnumerateSecurityEventSources.  I call it once to get back a count of 8 then initialize an array of AUTHZ_SOURCE_SCHEMA_REGISTRATION.  However I think I'm doing something wrong because when I  call Marshal.SizeOf()  I get an error saying it cannot be marshaled as an unmanaged structurel no meaninful size of offset can be computed.     I've seen StackOverflow answers talking about making sure the struct has the a attribute [StructLayout(LayoutKind.Sequential)]   and looking through  Vanara code it does.

**Comment by chrpai** [comment]
I think I found what I needed in the AuthzEnumerateSecurityEventSourcesTest  method  but I'm not sure it's best practice to just assume 200 is big enough.  I was assuming I'd have to call the API once to get the count and then allocate that many.   But I don't really know this API well enough to say that for a fact.

**Comment by dahall** [comment]
I need to spend some time investigating this, but my guess is that it is an error on my part. I'm traveling this week and may not be able to validate or invalidate this very quickly.

**Comment by dahall** [comment]
@chrpai Please see the new issue I created from your last message. There is no bug and I provided and example of how to use the method without overallocating memory.

**Comment by dahall** [comment]
I'm closing this as I have been adding a `static readonly Default` field for most structures that require initialization of any type. I'll continue this trend as I add and update. Thanks for the push.
